# Generated by Django 3.2.7 on 2021-09-29 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usersync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersync',
            name='last_update',
        ),
        migrations.AddField(
            model_name='usersync',
            name='last_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 29, 9, 54, 0, 128767, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
