# Generated by Django 3.2.7 on 2021-09-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210929_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersync',
            name='last_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
