# Generated by Django 3.2.7 on 2021-09-06 14:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activity_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
