# Generated by Django 3.2.7 on 2021-09-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activity_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='coordinates',
            new_name='polylines',
        ),
    ]
