# Generated by Django 3.2.7 on 2021-09-08 13:43

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20210906_1827'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('center_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('FINISHED', 'Finished')], default='IN_PROGRESS', max_length=12)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('map_position', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Locked'), (1, 'Unlocked')], default=0, max_length=1)),
                ('activity_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.activity')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='map.map')),
            ],
        ),
    ]
