# Generated by Django 3.2.7 on 2021-09-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='status',
            field=models.IntegerField(choices=[(0, 'Locked'), (1, 'Unlocked')], default=0),
        ),
    ]
