# Generated by Django 3.2.7 on 2021-09-09 08:37

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210906_1827'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0002_alter_zone_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_tiles_per_side', models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(64)])),
                ('center_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tile_size', models.FloatField(default=0.001)),
                ('status', models.CharField(choices=[('OPENED', 'Opened'), ('CLOSED', 'Closed')], default='OPENED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('registered_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('grid_position', models.PositiveIntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Locked'), (1, 'Unlocked')], default=0)),
                ('activity_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.activity')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='map.grid')),
            ],
        ),
        migrations.RemoveField(
            model_name='zone',
            name='activity_related',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='map',
        ),
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
