# Generated by Django 3.2.7 on 2021-09-09 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0003_auto_20210909_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='registered_users',
            field=models.ManyToManyField(related_name='registered_grids', to=settings.AUTH_USER_MODEL),
        ),
    ]
