# Generated by Django 3.2.7 on 2021-09-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='date_begin',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grid',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
