# Generated by Django 3.2.7 on 2021-09-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210924_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='date_begin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
