# Generated by Django 3.2.7 on 2021-09-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_grid_date_begin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='date_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
